# Generated by Django 4.2.3 on 2023-07-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox', models.BooleanField(default=False, verbose_name='체크')),
                ('todolist', models.TextField(verbose_name='내용')),
            ],
        ),
    ]
