# Generated by Django 4.2 on 2023-07-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox', models.BooleanField(default=False, verbose_name='체크')),
                ('todolist', models.TextField(verbose_name='내용')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
