# Generated by Django 4.2.3 on 2023-07-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='checkbox',
        ),
        migrations.AlterField(
            model_name='todo',
            name='todolist',
            field=models.CharField(max_length=100, verbose_name='내용'),
        ),
    ]
