# Generated by Django 4.2.3 on 2023-07-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='feeling',
            field=models.CharField(choices=[('1', '기쁨'), ('2', '행복'), ('3', '좋음'), ('4', '별로'), ('5', '화남'), ('6', '슬픔'), ('7', '보통')], default=2, max_length=2, verbose_name='기분'),
        ),
    ]
