# Generated by Django 4.2.3 on 2023-07-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_diaryimage_writer_alter_diaryimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='None/2023/07/09'),
        ),
    ]
