# Generated by Django 4.2.3 on 2023-07-09 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0005_alter_diaryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 9, 14, 2, 38, 838764, tzinfo=datetime.timezone.utc), verbose_name='업로드 날짜'),
            preserve_default=False,
        ),
    ]
